version: "3.5"
services:
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: domain-management
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./domainManagementUI:/app
    networks:
      - frontend
    env_file:
      - .env
networks:
  frontend:
    name: pca_frontend
