# mypy: ignore-errors
# flake8: noqa
# Generated by Selenium IDE
# Standard Python Libraries
import json
import time

# Third-Party Libraries
import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestBluecoat:
    def setup_method(self):
        self.driver = webdriver.Chrome(executable_path="../../drivers/chromedriver")
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_bluecoat(self):
        self.driver.get("https://sitereview.bluecoat.com/")
        self.driver.set_window_size(1200, 1325)
        self.driver.find_element(By.ID, "txtUrl").send_keys("example.com")
        self.driver.find_element(By.ID, "txtUrl").send_keys(Keys.ENTER)
        time.sleep(1)
        is_submitted_msg = self.driver.find_elements_by_xpath(
            "//*[contains(text(),'Only a single submission per site is needed unless the content differs')]"
        )
        if len(is_submitted_msg) > 0:
            print("Already been Submitted")
            return
        filter_dropdown = self.driver.find_element(
            By.CSS_SELECTOR, "#selFilteringService input"
        )
        filter_dropdown.click()
        filtering_service = filter_dropdown.find_element_by_xpath(
            "//*[contains(text(),'Blue Coat ProxyClient')]"
        )
        filtering_service.click()
        category_dropdown = self.driver.find_element(By.CSS_SELECTOR, "#txtCat1 input")
        category_dropdown.click()
        category_name = category_dropdown.find_element_by_xpath(
            "//*[contains(text(),'Technology/Internet')]"
        )
        scroll_to_category = ActionChains(self.driver).move_to_element(category_name)
        scroll_to_category.perform()
        category_name.click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("idahotester33@gmail.com")
        self.driver.find_element(By.ID, "emailcc").send_keys("idahotester33@gmail.com")
        time.sleep(1)
        self.driver.find_element(By.ID, "submit2").click()


test_bluecoat = TestBluecoat()
test_bluecoat.setup_method()
test_bluecoat.test_bluecoat()
