# mypy: ignore-errors
# flake8: noqa
# Generated by Selenium IDE
# Standard Python Libraries
import json
import os
import sys
import time

# Third-Party Libraries
from dotenv import load_dotenv

# Load environment variables from .env file
import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from twocaptcha import TwoCaptcha

load_dotenv(dotenv_path="../../.env")
api_key = os.getenv("TWO_CAPTCHA")


class TestFortiguard:
    def setup_method(self):
        self.driver = webdriver.Chrome(executable_path="../../drivers/chromedriver")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_fortiguard(self):
        self.driver.get("https://www.fortiguard.com/faq/wfratingsubmit")
        self.driver.set_window_size(1680, 979)
        self.driver.find_element(By.ID, "__agreementButton").click()
        time.sleep(3)
        self.driver.find_element(By.ID, "web_filter_rating_info_form_url").click()
        self.driver.find_element(By.ID, "web_filter_rating_info_form_url").click()
        self.driver.find_element(By.ID, "web_filter_rating_info_form_url").send_keys(
            "https://example.com"
        )
        wait = WebDriverWait(self.driver, 10)
        wait.until(
            EC.presence_of_element_located(
                (By.ID, "web_filter_rating_info_form_categorysuggestion")
            )
        )
        self.driver.find_element(
            By.ID, "web_filter_rating_info_form_categorysuggestion"
        ).click()
        dropdown = self.driver.find_element(
            By.ID, "web_filter_rating_info_form_categorysuggestion"
        )
        dropdown.find_element(By.XPATH, "//option[. = 'Health and Wellness']").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".page-section > .row:nth-child(2)"
        ).click()
        wait.until(
            EC.presence_of_element_located((By.ID, "web_filter_rating_info_form_name"))
        )
        self.driver.find_element(By.ID, "web_filter_rating_info_form_name").click()
        self.driver.find_element(By.ID, "web_filter_rating_info_form_name").send_keys(
            "Idaho Tester"
        )
        self.driver.find_element(By.ID, "web_filter_rating_info_form_email").send_keys(
            "idahotester33@gmail.com"
        )
        self.driver.find_element(
            By.ID, "web_filter_rating_info_form_companyname"
        ).send_keys("INL")
        recaptcha_element = self.driver.find_element(By.CLASS_NAME, "g-recaptcha")
        sitekey = recaptcha_element.get_attribute("data-sitekey")
        print(sitekey)

        solver = TwoCaptcha(api_key)
        try:
            result = solver.recaptcha(
                sitekey=sitekey, url="https://www.fortiguard.com/faq/wfratingsubmit"
            )

        except Exception as e:
            print(e)
        else:
            self.driver.execute_script(
                "document.getElementById('g-recaptcha-response').innerHTML='"
                + result["code"]
                + "';"
            )
            self.driver.find_element(
                By.ID, "web_filter_rating_info_form_submit"
            ).click()
            time.sleep(3)


fortiguard = TestFortiguard()
fortiguard.setup_method()
fortiguard.test_fortiguard()
