# mypy: ignore-errors
# flake8: noqa
# Generated by Selenium IDE
# Standard Python Libraries
import json
import os
import sys
import time

# Third-Party Libraries
import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from twocaptcha import TwoCaptcha


class TestTrendmicro:
    def setup_method(self):
        self.driver = webdriver.Chrome(executable_path="./drivers/chromedriver.exe")
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_trendmicro(self):
        self.driver.get("https://global.sitesafety.trendmicro.com/")
        self.driver.set_window_size(2576, 1416)
        self.driver.find_element(By.ID, "urlname").click()
        self.driver.find_element(By.ID, "urlname").click()
        self.driver.find_element(By.ID, "urlname").send_keys(
            "http://testingaccount.xyz/"
        )
        self.driver.find_element(By.ID, "getinfo").click()
        self.driver.find_element(By.ID, "myBtn").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".modal_content_2:nth-child(2) a"
        ).click()
        self.driver.find_element(By.CSS_SELECTOR, ".lightbg:nth-child(4) input").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".suggestoption > .radioinput"
        ).click()
        self.driver.find_element(By.ID, "radio5").click()
        self.driver.find_element(By.CSS_SELECTOR, ".General .normal").click()
        self.driver.find_element(By.CSS_SELECTOR, ".Business .normal").click()
        time.sleep(1)
        self.driver.find_element(
            By.CSS_SELECTOR, "#Business .child_row_01:nth-child(3) .radio_c1"
        ).click()
        self.driver.find_element(By.ID, "owner").click()
        self.driver.find_element(By.ID, "comments").click()
        self.driver.find_element(By.ID, "comments").send_keys(
            "Changing Website for customer"
        )
        self.driver.find_element(By.ID, "textfieldemail").send_keys(
            "barry.k.hansen@gmail.com"
        )
        self.getAndSolve("https://global.sitesafety.trendmicro.com/")
        self.driver.find_element(By.NAME, "send").click()
        self.driver.find_element(By.LINK_TEXT, "Check a URL").click()

    def getAndSolve(self, url):

        recaptcha_element = self.driver.find_element(By.CLASS_NAME, "g-recaptcha")
        sitekey = recaptcha_element.get_attribute("data-sitekey")
        print(sitekey)

        api_key = os.getenv("APIKEY_2CAPTCHA")
        solver = TwoCaptcha(api_key)
        try:
            result = solver.recaptcha(sitekey=sitekey, url=url)

        except Exception as e:
            print(e)
        else:
            self.driver.execute_script(
                "document.getElementById('g-recaptcha-response').innerHTML='"
                + result["code"]
                + "';"
            )
            time.sleep(3)


test = TestTrendmicro()
test.setup_method()
test.test_trendmicro()
